// [ru, en, tk]. Turkmen strings are a best-effort draft and need review by a native speaker.
export const ADMIN = {
  'app.admin': ['Униформа · Админ', 'Uniform · Admin', 'Uniform · Admin'],
  'nav.requests': ['Запросы', 'Requests', 'Haýyşlar'],
  'nav.guards': ['Охранники', 'Guards', 'Garawullar'],
  'nav.stock': ['Склад', 'Stock', 'Ammar'],
  'nav.planning': ['Планирование', 'Planning', 'Meýilnama'],
  'nav.groups': ['Группы', 'Groups', 'Toparlar'],
  'nav.sizes': ['Размеры', 'Sizes', 'Ölçegler'],
  'nav.reviews': ['Отзывы', 'Reviews', 'Syn-bahalar'],
  'nav.accounts': ['Аккаунты', 'Accounts', 'Hasaplar'],
  'nav.catalog': ['Справочники', 'Catalog', 'Sanawlar'],

  // requests
  'req.sub': ['Заявки охранников, группы и выдачи, ждущие подписи', 'Guard requests, groups and issuances waiting for a signature', 'Garawullaryň haýyşlary, toparlar we gol garaşýan bermeler'],
  'req.pending': ['Ждут подписи охранника', 'Waiting for the guard to sign', 'Garawulyň goluna garaşýar'],
  'req.pendingHint': ['Пока охранник не нажал «Подписать», вещи не выдаём', 'Hand nothing over until the guard has signed', 'Garawul gol çekýänçä zat bermäň'],
  'req.noPending': ['Нет выдач, ожидающих подписи', 'No issuances waiting for a signature', 'Gol garaşýan bermeler ýok'],
  'req.open': ['Открытые заявки', 'Open requests', 'Açyk haýyşlar'],
  'req.openHint': ['Группы — первыми', 'Groups come first', 'Toparlar ilki'],
  'req.noOpen': ['Открытых заявок нет', 'No open requests', 'Açyk haýyş ýok'],
  'req.recent': ['Недавно подписано', 'Recently signed', 'Ýaňy gol çekilenler'],
  'req.noRecent': ['Пока ничего', 'Nothing yet', 'Entek hiç zat ýok'],
  'req.signedAt': ['Подписано', 'Signed', 'Gol çekildi'],
  'req.created': ['Создано', 'Created', 'Döredildi'],
  'req.guard': ['Охранник', 'Guard', 'Garawul'],
  'req.items': ['Вещи', 'Items', 'Zatlar'],
  'req.item': ['Вещь', 'Item', 'Zat'],
  'req.size': ['Размер', 'Size', 'Ölçeg'],
  'req.qty': ['Кол-во', 'Qty', 'Sany'],
  'req.source': ['Источник', 'Source', 'Çeşme'],
  'req.status': ['Статус', 'Status', 'Ýagdaý'],
  'req.stock': ['Склад', 'Stock', 'Ammar'],
  'req.paper': ['Бумажный бланк', 'Paper form', 'Kagyz blank'],
  'req.paperForm': ['Бланк заполнен', 'Paper form done', 'Blank dolduryldy'],
  'req.paperDone': ['Бланк от {date}', 'Form dated {date}', 'Blank {date}'],
  'req.paperMissing': ['Нет бланка', 'No paper form', 'Blank ýok'],
  'req.reason': ['Причина', 'Reason', 'Sebäp'],
  'req.cancelIssuance': ['Отменить выдачу', 'Cancel issuance', 'Bermegi ýatyr'],
  'req.cancelAsk': ['Отменить эту выдачу? Резерв на складе снимется.', 'Cancel this issuance? The stock hold will be released.', 'Bu bermegi ýatyrýarsyňyzmy? Ammardaky rezerw aýrylar.'],
  'req.send': ['Отправить на подпись ({n})', 'Send for signature ({n})', 'Gola iber ({n})'],
  'req.sent': ['Отправлено охраннику на подпись', 'Sent to the guard for signature', 'Garawula gol üçin ugradyldy'],
  'req.inStock': ['Есть на складе', 'In stock', 'Ammarda bar'],
  'req.waiting': ['Ждёт поставки', 'Awaiting supply', 'Üpjünçiligi garaşýar'],
  'req.reservedGroup': ['Резерв группы', 'Group reserved', 'Topar üçin rezerw'],
  'req.groupPriority': ['Группа — приоритет', 'Group — priority', 'Topar — ileri tutulýar'],
  'req.signedToast': ['№{no} подписал выдачу', 'No. {no} signed', '№{no} gol çekdi'],

  // guards
  'guards.summary': ['Активных: {n} · около лимита: {near} · сверх лимита: {over}', 'Active: {n} · near limit: {near} · over limit: {over}', 'Işjeň: {n} · limite ýakyn: {near} · limitden geçen: {over}'],
  'guards.search': ['Поиск по номеру или имени', 'Search by number or name', 'Belgi ýa-da at boýunça gözleg'],
  'guards.showOff': ['Показать отключённых', 'Show disabled', 'Öçürilenleri görkez'],
  'guards.none': ['Охранников пока нет. Добавьте их в «Аккаунтах».', 'No guards yet. Add them under Accounts.', 'Entek garawul ýok. «Hasaplar» bölüminde goşuň.'],
  'guards.notFound': ['Такого охранника нет', 'No such guard', 'Beýle garawul ýok'],
  'guards.off': ['Отключён', 'Disabled', 'Öçürilen'],
  'guards.hired': ['Принят', 'Hired', 'Işe alnan'],
  'guards.issue': ['Выдать вручную / срочно', 'Issue manually / urgent', 'El bilen / gyssagly ber'],
  'guards.resetPin': ['Сбросить PIN', 'Reset PIN', 'PIN-i täzeden goý'],
  'guards.deactivate': ['Отключить', 'Disable', 'Öçür'],
  'guards.reactivate': ['Включить снова', 'Enable again', 'Täzeden işjeňleşdir'],
  'guards.limit': ['Лимит года', 'Year limit', 'Ýyl limiti'],
  'guards.fyReceived': ['Получено за фингод', 'Received this fiscal year', 'Maliýe ýylynda alnan'],
  'guards.left': ['Осталось', 'Left', 'Galan'],
  'guards.fyStart': ['Фингод с', 'Fiscal year from', 'Maliýe ýyly başlanýar'],
  'guards.itemsStatus': ['Что положено', 'What is due', 'Näme degişli'],
  'guards.size': ['Размер', 'Size', 'Ölçeg'],
  'guards.lastIssued': ['Выдано', 'Last issued', 'Soňky berlen'],
  'guards.dueOn': ['Положено с', 'Due from', 'Şondan degişli'],
  'guards.state': ['Статус', 'State', 'Ýagdaý'],
  'guards.neverIssued': ['Не выдавалось', 'Never issued', 'Berilmändir'],
  'guards.due': ['Пора менять', 'Due now', 'Wagty geldi'],
  'guards.notDue': ['Рано', 'Not yet', 'Entek ir'],
  'guards.sizeMissing': ['не указан', 'not set', 'görkezilmedi'],
  'guards.received': ['Что получил', 'What was received', 'Alanlary'],
  'guards.receivedHint': ['Только подписанные выдачи', 'Signed issuances only', 'Diňe gol çekilen bermeler'],
  'guards.sum': ['Сумма', 'Amount', 'Mukdary'],
  'guards.fyTotal': ['Итого за фингод', 'Fiscal-year total', 'Maliýe ýyly boýunça jemi'],
  'guards.nothingReceived': ['Ещё ничего не получено', 'Nothing received yet', 'Entek hiç zat alynmady'],
  'guards.sizes': ['Размеры', 'Sizes', 'Ölçegler'],
  'guards.resetAsk': ['Сбросить PIN охранника №{no}? Будет создан новый временный PIN.', 'Reset the PIN of guard No. {no}? A new temporary PIN will be created.', '№{no} garawulyň PIN-ini täzeden goýmalymy? Täze wagtlaýyn PIN döredilýär.'],
  'guards.newPinTitle': ['Новый PIN охранника №{no}', 'New PIN for guard No. {no}', '№{no} garawul üçin täze PIN'],
  'guards.newPinHint': ['Передайте охраннику лично. При первом входе он задаст свой.', 'Hand it over in person. The guard sets their own at first sign-in.', 'Ony göni özüne beriň. Ilkinji girişde ol öz PIN-ini goýar.'],
  'guards.noteLabel': ['Причина (обязательно)', 'Reason (required)', 'Sebäp (hökmany)'],
  'guards.issueTitle': ['Выдача охраннику №{no}', 'Issue to guard No. {no}', '№{no} garawula bermek'],
  'guards.issueHint': ['Охранник подпишет в своём приложении. Вещь, которую уже выдавали, повторно выдаётся только за утерю или непригодность.', 'The guard signs in their app. An item already issued can be issued again only if lost or unfit.', 'Garawul öz programmasynda gol çekýär. Eýýäm berlen zat gaýtadan diňe ýitirilen ýa-da ýaramsyz bolsa berilýär.'],
  'guards.kind': ['Основание выдачи', 'Reason for issuing', 'Bermegiň esasy'],
  'guards.kind.planned': ['По сроку замены', 'Scheduled replacement', 'Çalyşmak möhleti boýunça'],
  'guards.kind.hire': ['При приёме на работу', 'On hire', 'Işe alnanda'],
  'guards.kind.lost': ['Утеря', 'Lost', 'Ýitirilen'],
  'guards.kind.unfit': ['Непригодность', 'Unfit for use', 'Ýaramsyz'],
  'guards.repeatHint': ['Повторная выдача до срока: нужна объяснительная записка на бумаге (отметьте ниже) и пояснение здесь.', 'An early re-issue needs a written explanation on paper (tick below) and a note here.', 'Möhletinden öň gaýtadan bermek üçin kagyzda düşündiriş hat (aşakda belläň) we şu ýerde bellik gerek.'],
  'guards.urgent': ['Срочная выдача (без резерва)', 'Urgent issuance (no reservation)', 'Gyssagly bermek (rezerwsiz)'],
  'guards.urgentReason': ['Пояснение (электронная заметка)', 'Explanation (electronic note)', 'Düşündiriş (elektron bellik)'],
  'guards.sendSign': ['Отправить на подпись', 'Send for signature', 'Gola iber'],
  'guards.pickItems': ['Выберите хотя бы одну вещь', 'Pick at least one item', 'Azyndan bir zat saýlaň'],
  'sizes.when': ['Когда', 'When', 'Haçan'],
  'sizes.change': ['Изменение', 'Change', 'Üýtgeşme'],
  'sizes.initial': ['указан впервые: {v}', 'first set: {v}', 'ilkinji gezek: {v}'],
  'stock.availN': ['доступно {n}', '{n} available', '{n} elýeterli'],

  // stock
  'stock.summary': ['На складе {pieces} шт. на {value}', '{pieces} pieces in stock worth {value}', 'Ammarda {pieces} sany, bahasy {value}'],
  'stock.addOpening': ['Внести остаток', 'Add opening stock', 'Galyndy goş'],
  'stock.openingHint': ['Остаток, который уже лежит на складе. В бюджет этого фингода он не входит.', 'Stock that is already on the shelf. It does not count toward this fiscal year’s budget.', 'Eýýäm ammarda bolan zat. Bu maliýe ýylynyň býujetine girmeýär.'],
  'stock.levels': ['Остатки', 'Stock levels', 'Galyndylar'],
  'stock.levelsHint': ['Доступно = на складе − ждёт подписи − резерв групп', 'Available = on hand − awaiting signature − group reservations', 'Elýeterli = ammarda − gol garaşýan − topar rezerwi'],
  'stock.none': ['Склад пуст', 'Nothing in stock', 'Ammar boş'],
  'stock.onHand': ['На складе', 'On hand', 'Ammarda'],
  'stock.reserved': ['Резерв', 'Reserved', 'Rezerw'],
  'stock.available': ['Доступно', 'Available', 'Elýeterli'],
  'stock.batches': ['Партии', 'Batches', 'Partiýalar'],
  'stock.showBatches': ['Показать партии', 'Show batches', 'Partiýalary görkez'],
  'stock.received': ['Поступило', 'Received', 'Gelip gowşan'],
  'stock.left': ['Осталось', 'Left', 'Galan'],
  'stock.price': ['Цена', 'Price', 'Baha'],
  'stock.basis': ['Основание', 'Basis', 'Esas'],
  'stock.fromOrder': ['из заказа', 'from an order', 'sargytdan'],

  // planning
  'plan.fy': ['Фингод {from} — {to}', 'Fiscal year {from} – {to}', 'Maliýe ýyly {from} – {to}'],
  'plan.budget': ['Бюджет отряда', 'Squad budget', 'Toparyň býujeti'],
  'plan.pool': ['Пул ({n} охранников)', 'Pool ({n} guards)', 'Umumy býujet ({n} garawul)'],
  'plan.ordered': ['Заказано', 'Ordered', 'Sargyt edilen'],
  'plan.received': ['Получено', 'Received', 'Alnan'],
  'plan.inTransit': ['В пути', 'In transit', 'Ýolda'],
  'plan.remaining': ['Свободно', 'Remaining', 'Galan'],
  'plan.whatIf': ['Если закажем ещё, $', 'If we also order, $', 'Ýene sargyt etsek, $'],
  'plan.calc': ['Посчитать', 'Calculate', 'Hasapla'],
  'plan.after': ['Итого {sum} ({pct})', 'Total {sum} ({pct})', 'Jemi {sum} ({pct})'],
  'plan.orders': ['Заказы', 'Orders', 'Sargytlar'],
  'plan.forecast': ['Что нужно заказать', 'What to order', 'Näme sargyt etmeli'],
  'plan.forecastSub': ['Сколько охранников дойдёт до замены к дате, минус склад и то, что уже в пути', 'Guards due for a replacement by the date, minus stock and what is already on the way', 'Senä çenli çalyşmaly garawullar, ammar we ýolda bolanlary aýyrmak bilen'],
  'plan.forecastHint': ['Сроки считаются от даты начала выдачи: наземная — 6 месяцев, авиа — 1 месяц.', 'Dates count back from the issue date: land 6 months, air 1 month.', 'Seneler berme senesinden hasaplanýar: gury ýol 6 aý, awia 1 aý.'],
  'plan.newOrder': ['Новый заказ', 'New order', 'Täze sargyt'],
  'plan.order': ['Заказ от', 'Order of', 'Sargyt'],
  'plan.noOrders': ['В этом фингоде заказов ещё нет', 'No orders in this fiscal year yet', 'Bu maliýe ýylynda entek sargyt ýok'],
  'plan.orderedOn': ['Дата заказа', 'Order date', 'Sargyt senesi'],
  'plan.shipping': ['Доставка', 'Shipping', 'Eltip bermek'],
  'plan.expected': ['Ожидается', 'Expected', 'Garaşylýar'],
  'plan.late': ['просрочено', 'overdue', 'gijikdi'],
  'plan.basis': ['Основание заказа', 'Order basis', 'Sargydyň esasy'],
  'plan.basisNote': ['Пояснение', 'Comment', 'Düşündiriş'],
  'plan.ref': ['Номер закупки', 'Procurement ref.', 'Satyn alyş belgisi'],
  'plan.notes': ['Заметка', 'Notes', 'Bellik'],
  'plan.pcs': ['шт.', 'pcs', 'sany'],
  'plan.unitPrice': ['Цена за шт., $', 'Unit price, $', 'Bahasy, $'],
  'plan.addLine': ['Добавить строку', 'Add a line', 'Setir goş'],
  'plan.total': ['Итого', 'Total', 'Jemi'],
  'plan.noLines': ['Добавьте хотя бы одну строку', 'Add at least one line', 'Azyndan bir setir goşuň'],
  'plan.change': ['Изменить кол-во', 'Change qty', 'Sany üýtget'],
  'plan.newQty': ['Новое количество', 'New quantity', 'Täze sany'],
  'plan.was': ['было {n}', 'was {n}', 'öň {n}'],
  'plan.left': ['Осталось', 'Left', 'Galan'],
  'plan.closed': ['закрыто', 'closed', 'ýapyldy'],
  'plan.closeRest': ['Закрыть остаток', 'Close the rest', 'Galanyny ýap'],
  'plan.closeNote': ['Не придёт {n} шт. — объясните почему', '{n} pcs will not arrive — say why', '{n} sany gelmeýär — sebäbini ýazyň'],
  'plan.stillComing': ['Ещё в пути', 'Still coming', 'Entek gelmedik'],
  'plan.receiveQty': ['Пришло', 'Arrived', 'Geldi'],
  'plan.deliveryDate': ['Дата поставки', 'Delivery date', 'Gowşuryş senesi'],
  'plan.deliveryNote': ['Заметка к поставке', 'Delivery note', 'Gowşuryş belligi'],
  'plan.saveDelivery': ['Принять поставку', 'Record delivery', 'Gowşurylyşy ýazyň'],
  'plan.bonusHint': ['Всё, что пришло сверх заказа, ложится на склад как бонус по цене $0.', 'Anything above the ordered amount goes on the shelf as a bonus at $0.', 'Sargytdan artyk gelen zat $0 bahadan bonus hökmünde ammara goşulýar.'],
  'plan.bonus': ['бонус', 'bonus', 'bonus'],
  'plan.deliveries': ['Поставки', 'Deliveries', 'Gowşurylyşlar'],
  'plan.items': ['Что пришло', 'What arrived', 'Näme geldi'],
  'plan.cancelOrder': ['Отменить заказ', 'Cancel order', 'Sargydy ýatyr'],
  'plan.cancelAsk': ['Отменить заказ целиком? Это можно сделать, пока ничего не получено.', 'Cancel the whole order? Possible only while nothing has been received.', 'Sargydy doly ýatyrmalymy? Entek hiç zat alynmadyk bolsa bolýar.'],
  'plan.allSeasons': ['Все сезоны', 'All seasons', 'Ähli pasyllar'],
  'plan.forDate': ['К дате', 'By date', 'Senä çenli'],
  'plan.due': ['Пора менять', 'Due', 'Wagty gelen'],
  'plan.coming': ['В пути', 'On the way', 'Ýolda'],
  'plan.toOrder': ['Заказать', 'To order', 'Sargyt etmeli'],
  'plan.orderBy': ['Заказать до', 'Order by', 'Şu senä çenli sargyt'],
  'plan.recommend': ['Что делать', 'Action', 'Hereket'],
  'plan.recLand': ['Успеть наземной', 'Land still works', 'Gury ýol ýetýär'],
  'plan.recAir': ['Только авиа', 'Air only', 'Diňe awia'],
  'plan.recLate': ['Уже не успеваем', 'Too late', 'Gijä galdy'],
  'plan.covered': ['Покрыто', 'Covered', 'Üpjün'],
  'plan.noNeed': ['К этой дате заменять никому не нужно', 'Nobody is due by this date', 'Bu seneden öň hiç kim çalyşmaly däl'],
  'plan.noSize': ['размер не указан', 'size not set', 'ölçeg görkezilmedi'],

  // season banners
  'season.soonLand': ['{season}: выдача с {date}. Наземной доставкой заказать до {land}, авиа — до {air}.', '{season}: issue starts {date}. Order by {land} for land shipping, {air} for air.', '{season}: berme {date} başlanýar. Gury ýol bilen {land} çenli, awia bilen {air} çenli sargyt ediň.'],
  'season.soonAir': ['{season}: выдача с {date}. Наземная уже не успевает — авиа до {air}.', '{season}: issue starts {date}. Land shipping is too late — air by {air}.', '{season}: berme {date} başlanýar. Gury ýol gijä galdy — awia {air} çenli.'],
  'season.late': ['{season}: выдача с {date}. К сроку уже не успеть.', '{season}: issue starts {date}. It is too late to deliver in time.', '{season}: berme {date} başlanýar. Wagtynda ýetirip bolmaz.'],

  // groups
  'groups.sub': ['Групповые брони и время выдачи', 'Group reservations and pickup times', 'Topar rezerwleri we bermek wagty'],
  'groups.slots': ['Время выдачи', 'Pickup slots', 'Bermek wagtlary'],
  'groups.slotsHint': ['Группы выбирают из этих слотов (на завтра и послезавтра)', 'Groups pick from these slots (tomorrow and the day after)', 'Toparlar şu wagtlardan saýlaýar (ertir we birigün)'],
  'groups.slotTime': ['Дата и время', 'Date and time', 'Sene we wagt'],
  'groups.slotNote': ['Заметка', 'Note', 'Bellik'],
  'groups.addSlot': ['Добавить слот', 'Add slot', 'Wagt goş'],
  'groups.delSlot': ['Удалить этот слот?', 'Delete this slot?', 'Bu wagty pozmalymy?'],
  'groups.noSlots': ['Слотов нет', 'No slots', 'Wagt ýok'],
  'groups.active': ['Активные группы', 'Active groups', 'Işjeň toparlar'],
  'groups.noActive': ['Активных групп нет', 'No active groups', 'Işjeň topar ýok'],
  'groups.past': ['Прошлые группы', 'Past groups', 'Öňki toparlar'],
  'groups.head': ['Старший', 'Head', 'Baş'],
  'groups.members': ['Участники', 'Members', 'Agzalar'],
  'groups.slot': ['Время', 'Time', 'Wagt'],
  'groups.until': ['Действует до', 'Valid until', 'Şu wagta çenli'],

  // sizes, reviews
  'sizes.sub': ['Кто и когда поменял размер', 'Who changed a size, and when', 'Kim haçan ölçegi üýtgetdi'],
  'sizes.hideInitial': ['Скрыть первые записи', 'Hide first entries', 'Ilkinji ýazgylary ýaşyr'],
  'sizes.date': ['Дата', 'Date', 'Sene'],
  'sizes.what': ['Что изменено', 'What changed', 'Näme üýtgedi'],
  'sizes.new': ['новое', 'new', 'täze'],
  'sizes.none': ['Изменений нет', 'No changes', 'Üýtgeşme ýok'],
  'reviews.sub': ['Оценки вещей. Авторы анонимны.', 'Item ratings. Authors are anonymous.', 'Zatlaryň bahalary. Awtorlar näbelli.'],
  'reviews.rating': ['Оценка', 'Rating', 'Baha'],
  'reviews.votes': ['Голосов', 'Votes', 'Ses'],
  'reviews.comment': ['Комментарий', 'Comment', 'Düşündiriş'],
  'reviews.date': ['Дата', 'Date', 'Sene'],
  'reviews.none': ['Отзывов пока нет', 'No reviews yet', 'Entek syn ýok'],

  // accounts
  'acc.subOwner': ['Админы, GSO и охранники', 'Admins, GSO and guards', 'Administratorlar, GSO we garawullar'],
  'acc.subAdmin': ['Вы можете создавать и сбрасывать PIN охранников', 'You can create guards and reset their PINs', 'Garawullary döredip we PIN-lerini täzeläp bilersiňiz'],
  'acc.ownerOnly': ['Админов и GSO ведут только главные админы.', 'Only main admins manage admins and GSO accounts.', 'Administratorlary we GSO diňe baş administratorlar dolandyrýar.'],
  'acc.staff': ['Админы и GSO', 'Admins and GSO', 'Administratorlar we GSO'],
  'acc.create': ['Создать аккаунт', 'Create account', 'Hasap döret'],
  'acc.created': ['Аккаунт создан', 'Account created', 'Hasap döredildi'],
  'acc.bulk': ['Загрузить список охранников', 'Import guards', 'Garawullary ýükle'],
  'acc.bulkHint': ['Номера охранников: диапазон (1-100) или по одному в строке. Каждому будет создан временный PIN. Имена не нужны.', 'Guard numbers: a range (1-100) or one per line. A temporary PIN is created for each. No names needed.', 'Garawul belgileri: aralyk (1-100) ýa-da her setirde biri. Hersine wagtlaýyn PIN döredilýär. Ady gerek däl.'],
  'acc.bulkRun': ['Создать', 'Create', 'Döret'],
  'acc.bulkDone': ['Создано: {ok}, с ошибкой: {fail}', 'Created: {ok}, failed: {fail}', 'Döredildi: {ok}, ýalňyş: {fail}'],
  'acc.badLine': ['Не понял строку', 'Cannot read this line', 'Setiri düşünmedim'],
  'acc.pinsOnce': ['PIN показаны один раз. Скачайте или распечатайте и раздайте лично.', 'PINs are shown once. Download or print them and hand them out in person.', 'PIN-ler bir gezek görkezilýär. Ýükläp ýa-da çap edip, göni ellerine beriň.'],
  'acc.print': ['Печать', 'Print', 'Çap et'],
  'acc.login': ['Логин', 'Login', 'Login'],
  'acc.name': ['Имя', 'Name', 'Ady'],
  'acc.role': ['Роль', 'Role', 'Roly'],
  'acc.guardNo': ['Номер охранника', 'Guard number', 'Garawulyň belgisi'],
  'acc.hired': ['Дата приёма', 'Hire date', 'Işe alnan senesi'],
  'acc.pinAuto': ['Временный PIN из 6 цифр создаётся автоматически.', 'A temporary 6-digit PIN is generated automatically.', 'Wagtlaýyn 6 sanly PIN awtomatiki döredilýär.'],
  'acc.tempPassword': ['Временный пароль', 'Temporary password', 'Wagtlaýyn parol'],
  'acc.makeOwner': ['Главный админ', 'Main admin', 'Baş administrator'],
  'acc.reset': ['Сбросить пароль', 'Reset password', 'Paroly täzeden goý'],
  'acc.resetHint': ['Человек задаст свой пароль при следующем входе.', 'The person sets their own at the next sign-in.', 'Adam indiki girişde öz paroluny goýar.'],
  'acc.deactivate': ['Отключить', 'Disable', 'Öçür'],
  'acc.reactivate': ['Включить', 'Enable', 'Işjeňleşdir'],
  'acc.noteLabel': ['Причина (обязательно)', 'Reason (required)', 'Sebäp (hökmany)'],
  'acc.secretOnce': ['Показано один раз. Передайте лично.', 'Shown once. Hand it over in person.', 'Bir gezek görkezilýär. Göni özüne beriň.'],

  // catalog
  'catalog.sub': ['Вещи, размеры, сезоны, основания заказа и настройки', 'Items, sizes, seasons, order bases and settings', 'Zatlar, ölçegler, pasyllar, sargyt esaslary we sazlamalar'],
  'catalog.items': ['Вещи', 'Items', 'Zatlar'],
  'catalog.sizeTypes': ['Типы размеров', 'Size types', 'Ölçeg görnüşleri'],
  'catalog.seasons': ['Сезоны', 'Seasons', 'Pasyllar'],
  'catalog.bases': ['Основания заказа', 'Order bases', 'Sargyt esaslary'],
  'catalog.settings': ['Настройки', 'Settings', 'Sazlamalar'],
  'catalog.addItem': ['Добавить вещь', 'Add item', 'Zat goş'],
  'catalog.addType': ['Добавить тип размера', 'Add size type', 'Ölçeg görnüşini goş'],
  'catalog.addBase': ['Добавить основание', 'Add basis', 'Esas goş'],
  'catalog.noItems': ['Вещей пока нет', 'No items yet', 'Entek zat ýok'],
  'catalog.noBases': ['Оснований пока нет', 'No bases yet', 'Entek esas ýok'],
  'catalog.noDelete': ['Вещь нельзя удалить — только отключить, чтобы история осталась.', 'An item cannot be deleted, only disabled, so history stays intact.', 'Zady pozup bolmaýar, diňe öçürip bolýar — taryh saklanýar.'],
  'catalog.sku': ['Артикул', 'SKU', 'Artikul'],
  'catalog.season': ['Сезон', 'Season', 'Pasyl'],
  'catalog.sizeType': ['Тип размера', 'Size type', 'Ölçeg görnüşi'],
  'catalog.wear': ['Срок носки', 'Wear period', 'Geýiş möhleti'],
  'catalog.wearMonths': ['Срок носки, лет', 'Wear period, years', 'Geýiş möhleti, ýyl'],
  'catalog.years1': ['год', 'year', 'ýyl'],
  'catalog.years2': ['года', 'years', 'ýyl'],
  'catalog.years5': ['лет', 'years', 'ýyl'],
  'catalog.budget': ['В бюджете', 'In budget', 'Býujetde'],
  'catalog.yes': ['да', 'yes', 'hawa'],
  'catalog.no': ['нет', 'no', 'ýok'],
  'catalog.inBudget': ['Входит в бюджет охранника', 'Counts toward the guard budget', 'Garawulyň býujetine girýär'],
  'catalog.inBudgetHint': ['Одежда и обувь входят, снаряжение (чехлы, ремень, жетон и т. д.) нет: цены на него вводятся и видны (для сравнения закупок), но в бюджет и итоги не входят. Остатки на складе видны в любом случае.', 'Clothing and footwear count, equipment (holders, duty belt, badge, etc.) does not: its prices are recorded and shown (to compare purchases) but excluded from budgets and totals. Stock is shown either way.', 'Egin-eşik we aýakgap girýär, enjam (gaplar, guşak, nyşan we ş.m.) girmeýär: onuň bahalary ýazylýar we görkezilýär (satyn almalary deňeşdirmek üçin), emma býujete we jemlere girmeýär. Ammardaky galyndy ýene-de görünýär.'],
  'guards.outOfBudget': ['вне бюджета', 'not in budget', 'býujete girmeýär'],
  'plan.inBudgetPart': ['из них в бюджете', 'of which in budget', 'şondan býujetde'],
  'common.edit': ['Изменить', 'Edit', 'Üýtgetmek'],
  'item.notFound': ['Вещь не найдена', 'Item not found', 'Haryt tapylmady'],
  'item.priceChart': ['Цена за штуку по закупкам', 'Unit price by purchase', 'Satyn almalar boýunça bahasy'],
  'item.mode.cal': ['По календарным годам', 'Calendar years', 'Senenama ýyllary'],
  'item.mode.fy': ['По финансовым годам (сен–авг)', 'Fiscal years (Sep–Aug)', 'Maliýe ýyllary (sen–awg)'],
  'item.inBudget': ['в бюджете охранника', 'counts toward guard budget', 'garawulyň býujetinde'],
  'item.onHand': ['На складе, шт.', 'In stock, pcs', 'Ammarda, sany'],
  'item.bought': ['Закуплено, шт.', 'Purchased, pcs', 'Satyn alnan, sany'],
  'item.spent': ['Потрачено на закупки', 'Spent on purchases', 'Satyn almaga harçlanan'],
  'item.issuedTotal': ['Выдано, шт.', 'Issued, pcs', 'Berlen, sany'],
  'item.lastPrice': ['Последняя цена', 'Latest price', 'Soňky baha'],
  'item.priceByYear': ['Закупки и цена по годам', 'Purchases and price by year', 'Ýyllar boýunça satyn almalar we baha'],
  'item.priceHint': ['Средняя цена взвешена по количеству; изменение — к прошлому году с закупками.', 'Average price is weighted by quantity; change is against the previous year with purchases.', 'Ortaça baha mukdar boýunça hasaplanýar; üýtgeme öňki ýyl bilen deňeşdirilýär.'],
  'item.year': ['Год', 'Year', 'Ýyl'],
  'item.fy': ['Финансовый год', 'Fiscal year', 'Maliýe ýyly'],
  'item.qty': ['Куплено, шт.', 'Bought, pcs', 'Alnan, sany'],
  'item.sum': ['Сумма', 'Total', 'Jemi'],
  'item.min': ['Мин. цена', 'Min price', 'Iň pes baha'],
  'item.avg': ['Средняя цена', 'Avg price', 'Ortaça baha'],
  'item.max': ['Макс. цена', 'Max price', 'Iň ýokary baha'],
  'item.change': ['Изменение', 'Change', 'Üýtgeme'],
  'item.noPurchases': ['Закупок и остатков по этой вещи пока нет.', 'No purchases or opening stock for this item yet.', 'Bu haryt boýunça entek satyn alma ýok.'],
  'item.purchases': ['Все закупки', 'All purchases', 'Ähli satyn almalar'],
  'item.date': ['Дата', 'Date', 'Sene'],
  'item.doc': ['Закупочный документ и основание', 'Procurement document and basis', 'Satyn alma resminamasy we esas'],
  'item.ordered': ['Заказано', 'Ordered', 'Sargyt edilen'],
  'item.received': ['Получено', 'Received', 'Alnan'],
  'item.opening': ['Остаток на начало', 'Opening stock', 'Başlangyç galyndy'],
  'item.shipping': ['Доставка', 'Shipping', 'Eltip bermek'],
  'item.issuedByYear': ['Выдачи по годам', 'Issued by year', 'Ýyllar boýunça berlenler'],
  'item.atHire': ['При приёме', 'On hire', 'Işe alnanda'],
  'item.planned': ['Замена по сроку и прочее', 'Scheduled and other', 'Möhleti boýunça we başga'],
  'item.lostUnfit': ['Утеря / непригодность', 'Lost / unfit', 'Ýitirilen / ýaramsyz'],
  'item.bySize': ['Выдано по размерам (за всё время)', 'Issued by size (all time)', 'Ölçegler boýunça (ähli wagt)'],
  'item.noIssues': ['Эту вещь ещё не выдавали.', 'This item has not been issued yet.', 'Bu haryt entek berilmedi.'],
  'item.lastIssues': ['Последние выдачи', 'Latest issuances', 'Soňky bermeler'],
  'item.lastIssuesHint': ['Последние 30, только подписанные', 'Latest 30, signed only', 'Soňky 30, diňe gol çekilen'],
  'gstat.title': ['Статистика по годам', 'Statistics by year', 'Ýyllar boýunça statistika'],
  'gstat.hint': ['Финансовый год сентябрь–август. Потрачено считается только по одежде и обуви.', 'Fiscal year runs September–August. Spent counts clothing and footwear only.', 'Maliýe ýyly sentýabr–awgust. Harçlanan diňe egin-eşik we aýakgap boýunça.'],
  'gstat.fy': ['Финансовый год', 'Fiscal year', 'Maliýe ýyly'],
  'gstat.pieces': ['Получено, шт.', 'Received, pcs', 'Alnan, sany'],
  'gstat.spent': ['Потрачено', 'Spent', 'Harçlanan'],
  'gstat.pct': ['% лимита', '% of limit', 'Çäkden %'],
  'gstat.urgent': ['Срочных выдач', 'Urgent issues', 'Gyssagly bermeler'],
  'gstat.equip': ['Снаряжение, шт.', 'Equipment, pcs', 'Enjam, sany'],
  'gstat.byItem': ['По вещам за всё время', 'By item, all time', 'Harytlar boýunça, ähli wagt'],
  'gstat.times': ['Раз выдано', 'Times issued', 'Gezek berlen'],
  'gstat.last': ['Последняя выдача', 'Last issued', 'Soňky bermek'],
  'catalog.once': ['один раз', 'once', 'bir gezek'],
  'catalog.months': ['мес.', 'mo.', 'aý'],
  'catalog.norm': ['Норма', 'Norm', 'Kada'],
  'catalog.active': ['Активна', 'Active', 'Işjeň'],
  'catalog.code': ['Код', 'Code', 'Kod'],
  'catalog.options': ['Размеры', 'Sizes', 'Ölçegler'],
  'catalog.optionsHint': ['Список размеров через запятую', 'Sizes separated by commas', 'Ölçegler otur bilen aýrylan'],
  'catalog.optionsWarn': ['Уже введённые охранниками размеры не меняются, даже если убрать их из списка.', 'Sizes guards already entered stay as they are, even if you remove them from the list.', 'Garawullaryň eýýäm giren ölçegleri sanawdan aýyrsaňyz hem üýtgemeýär.'],
  'catalog.order': ['Порядок', 'Order', 'Tertip'],
  'catalog.issueFrom': ['Выдача с', 'Issue from', 'Bermek başlanýar'],
  'catalog.issueUntil': ['Выдача до', 'Issue until', 'Bermek gutarýar'],
  'catalog.seasonsHint': ['От этих дат считаются предупреждения о заказе', 'Order warnings are counted back from these dates', 'Sargyt duýduryşlary şu seneden hasaplanýar'],
  'catalog.badDates': ['Дата «до» раньше даты «с»', 'The end date is before the start date', 'Gutarýan sene başlanýan seneden öň'],
  'catalog.fillAll': ['Заполните все поля', 'Fill in all fields', 'Ähli meýdanlary dolduryň'],
  'catalog.badThresholds': ['Пороги должны идти по возрастанию и не быть выше 100', 'Thresholds must increase and stay at or below 100', 'Çäkler ýokarlanmaly we 100-den geçmeli däl'],
  'catalog.s.limit': ['Лимит на охранника в год', 'Per-guard yearly limit', 'Garawul üçin ýyllyk limit'],
  'catalog.s.land': ['Наземная доставка, дней', 'Land shipping, days', 'Gury ýol, gün'],
  'catalog.s.air': ['Авиадоставка, дней', 'Air shipping, days', 'Awia eltip bermek, gün'],
  'catalog.s.green': ['Зелёная шкала до', 'Green up to', 'Ýaşyl şu ýere çenli'],
  'catalog.s.yellow': ['Жёлтая до', 'Yellow up to', 'Sary şu ýere çenli'],
  'catalog.s.rust': ['Ржавая до (дальше красная)', 'Rust up to (red beyond)', 'Pas reňk şu ýere çenli (soň gyzyl)'],
};
