// Guard app (g.*) and GSO app (gso.*). Turkmen is a best-effort draft and needs review by a native speaker.
export const APPS = {
  'g.title': ['Униформа', 'Uniform', 'Uniform'],
  'g.tab.home': ['Мои вещи', 'My items', 'Zatlarym'],
  'g.tab.group': ['Группа', 'Group', 'Topar'],
  'g.tab.sizes': ['Размеры', 'Sizes', 'Ölçegler'],
  'g.tab.reviews': ['Отзывы', 'Reviews', 'Syn-bahalar'],
  'g.hello': ['Охранник №{no}', 'Guard No. {no}', 'Garawul №{no}'],
  'g.homeSub': ['Что вам положено и что можно запросить', 'What you are due and what you can request', 'Näme degişli we näme haýyş edip bolýar'],
  'g.myItems': ['Моя форма', 'My uniform', 'Meniň eşigim'],
  'g.noItems': ['Список вещей пока пуст', 'The item list is empty for now', 'Zatlaryň sanawy entek boş'],
  'g.received': ['Что я получил', 'What I have received', 'Alanlarym'],
  'g.noneReceived': ['Пока ничего не получено', 'Nothing received yet', 'Entek hiç zat alynmady'],
  'g.size': ['размер', 'size', 'ölçeg'],
  'g.sizeNone': ['размер не указан', 'size not set', 'ölçeg görkezilmedi'],
  'g.oneSize': ['один размер', 'one size', 'bir ölçeg'],
  'g.last': ['выдано {date}', 'issued {date}', 'berlen {date}'],
  'g.due': ['Пора менять', 'Due for replacement', 'Çalyşmaly wagty geldi'],
  'g.dueFirst': ['Положено', 'You are due', 'Degişli'],
  'g.notBefore': ['Не раньше {date}', 'Not before {date}', '{date} çenli däl'],
  'g.notDue': ['Пока не положено', 'Not due yet', 'Entek degişli däl'],
  'g.request': ['Запросить', 'Request', 'Haýyş et'],
  'g.setSize': ['Указать размер', 'Set size', 'Ölçegi görkez'],
  'g.reqSent': ['Заявка отправлена', 'Request sent', 'Haýyş iberildi'],
  'g.reqGroup': ['В заявке группы', 'In a group request', 'Topar haýyşynda'],
  'g.reqDone': ['Заявка отправлена', 'Request sent', 'Haýyş iberildi'],
  'g.cancelReq': ['Отменить', 'Cancel', 'Ýatyr'],
  'g.cancelReqAsk': ['Отменить заявку?', 'Cancel this request?', 'Haýyşy ýatyrmalymy?'],
  'g.signNow': ['Нужна ваша подпись', 'Your signature is needed', 'Goluňyz gerek'],
  'g.signHint': ['Подпишите, когда вещи уже у вас в руках. Без подписи ничего не выдаётся.', 'Sign once the items are in your hands. Nothing is handed out without a signature.', 'Zatlar eliňize düşenden soň gol çekiň. Gol çekilmese zat berilmeýär.'],
  'g.urgentNote': ['Срочная выдача — заполните ещё и бумажный бланк.', 'Urgent issuance — the paper form must be filled in as well.', 'Gyssagly bermek — kagyz blany hem dolduryň.'],
  'g.sign': ['Подписать', 'Sign', 'Gol çek'],
  'g.signTitle': ['Подтвердите подпись', 'Confirm your signature', 'Goluňyzy tassyklaň'],
  'g.signAsk': ['Вы получили: {items}?', 'Did you receive: {items}?', 'Aldyňyzmy: {items}?'],
  'g.signed': ['Подписано', 'Signed', 'Gol çekildi'],

  'g.groupSub': ['Группа от 3 человек получает вещи в назначенное время, и вещи для неё откладываются.', 'A group of 3 or more collects at a set time, and the stock is held for it.', '3 ýa-da ondan köp adamlyk topar bellenen wagtda alýar, zatlar onuň üçin goýulýar.'],
  'g.noGroup': ['Вы не в группе', 'You are not in a group', 'Siz toparda däl'],
  'g.groupRules': ['Создайте группу, позовите коллег по номеру и выберите время. Группа действует до 18:00 (если создана вечером — до 18:00 следующего дня). Если к времени выдачи подтвердили меньше 3 человек, группа не действует.', 'Create a group, invite colleagues by number and pick a time. A group is valid until 18:00 (if created in the evening, until 18:00 the next day). If fewer than 3 people have confirmed by pickup time, the group does not apply.', 'Topar dörediň, kärdeşleri belgisi boýunça çagyryň we wagt saýlaň. Topar sagat 18:00-a çenli güýçde (agşam döredilse, ertesi gün 18:00-a çenli). Wagtynda 3 adamdan az tassyklasa, topar güýje girmeýär.'],
  'g.createGroup': ['Создать группу', 'Create a group', 'Topar döret'],
  'g.groupCreated': ['Группа создана', 'Group created', 'Topar döredildi'],
  'g.myGroup': ['Моя группа', 'My group', 'Meniň toparym'],
  'g.waitConfirm': ['Ждём подтверждений', 'Awaiting confirmations', 'Tassyklamalar garaşylýar'],
  'g.head': ['старший', 'head', 'baş'],
  'g.validUntil': ['Действует до {time}', 'Valid until {time}', '{time} çenli güýçde'],
  'g.needThree': ['Подтвердили время: {n} из {joined}. Нужно не меньше 3.', 'Confirmed the time: {n} of {joined}. At least 3 are needed.', 'Wagty tassyklady: {n} / {joined}. Azyndan 3 gerek.'],
  'g.slotChosen': ['Время выдачи: {when}', 'Pickup time: {when}', 'Bermek wagty: {when}'],
  'g.slotTolerance': ['Приходите в течение ±30 минут от этого времени.', 'Come within ±30 minutes of this time.', 'Şu wagtdan ±30 minut aralygynda geliň.'],
  'g.confirmSlot': ['Подтверждаю это время', 'I confirm this time', 'Bu wagty tassyklaýaryn'],
  'g.confirmedToast': ['Время подтверждено', 'Time confirmed', 'Wagt tassyklandy'],
  'g.pickSlot': ['Выберите время выдачи', 'Choose a pickup time', 'Bermek wagtyny saýlaň'],
  'g.noSlots': ['Админ ещё не назначил время на завтра и послезавтра', 'The admin has not set times for tomorrow or the day after yet', 'Admin ertir we birigün üçin entek wagt bellemedi'],
  'g.pickSlotFirst': ['Сначала выберите время', 'Choose a time first', 'Ilki wagt saýlaň'],
  'g.saveSlot': ['Выбрать это время', 'Choose this time', 'Bu wagty saýla'],
  'g.slotSet': ['Время выбрано, участникам нужно подтвердить', 'Time chosen — members must confirm', 'Wagt saýlandy — agzalar tassyklamaly'],
  'g.invite': ['Позвать коллегу', 'Invite a colleague', 'Kärdeşi çagyr'],
  'g.guardNo': ['Номер охранника', 'Guard number', 'Garawulyň belgisi'],
  'g.inviteBtn': ['Позвать', 'Invite', 'Çagyr'],
  'g.inviteSent': ['Приглашение отправлено', 'Invitation sent', 'Çakylyk iberildi'],
  'g.noSuchGuard': ['Такого номера нет', 'No such number', 'Beýle belgi ýok'],
  'g.groupItems': ['Что заказываем группой', 'What the group orders', 'Topar näme sargyt edýär'],
  'g.groupItemsHint': ['Вещи из заявок группы откладываются на складе до выдачи.', 'Items in group requests are held in stock until pickup.', 'Topar haýyşlaryndaky zatlar berilýänçä ammarda goýulýar.'],
  'g.nothingDue': ['Сейчас ничего не положено', 'Nothing is due right now', 'Häzir hiç zat degişli däl'],
  'g.addToGroup': ['В группу', 'Add', 'Topara goş'],
  'g.removeFromGroup': ['Убрать', 'Remove', 'Aýyr'],
  'g.transfer': ['Передать роль старшего', 'Hand over the head role', 'Baş roly ber'],
  'g.transferHint': ['Новый старший должен собрать группу не меньше чем из 3 человек, иначе она распадётся.', 'The new head must keep the group at 3 or more, otherwise it dissolves.', 'Täze baş toparyň azyndan 3 adam bolmagyny üpjün etmeli, ýogsam topar dargaýar.'],
  'g.leave': ['Выйти из группы', 'Leave the group', 'Topardan çyk'],
  'g.leaveAsk': ['Выйти из группы?', 'Leave the group?', 'Topardan çykmalymy?'],
  'g.leaveHeadAsk': ['Вы старший. Если выйти, роль перейдёт другому или группа распадётся. Выйти?', 'You are the head. If you leave, the role passes on or the group dissolves. Leave?', 'Siz baş. Çyksaňyz, roly başga biri alar ýa-da topar dargar. Çykmalymy?'],
  'g.invited': ['Вас зовут в группу', 'You are invited to a group', 'Sizi topara çagyrýarlar'],
  'g.invitedBy': ['Приглашает №{no} {name}', 'Invited by No. {no} {name}', '№{no} {name} çagyrýar'],
  'g.invitedAnon': ['Вас пригласили в группу получения формы', 'You have been invited to a uniform pickup group', 'Sizi eşik almak toparyna çagyrdylar'],
  'g.accept': ['Принять', 'Accept', 'Kabul et'],
  'g.decline': ['Отказаться', 'Decline', 'Ret et'],

  'g.sizesSub': ['Выберите свой размер. Он сохраняется сразу, админ видит изменения.', 'Choose your size. It is saved at once and the admin sees changes.', 'Ölçegiňizi saýlaň. Ol ýerinde saklanýar, admin üýtgeşmeleri görýär.'],
  'g.sizeSaved': ['Размер сохранён', 'Size saved', 'Ölçeg saklandy'],

  'g.reviewsSub': ['Оцените вещи, которые получили. Админы не видят, кто написал отзыв.', 'Rate the items you have received. Admins cannot see who wrote a review.', 'Alan zatlaryňyzy baha beriň. Adminler syny kimiň ýazanyny görmeýär.'],
  'g.noReviewItems': ['Оценить можно то, что уже получено', 'You can rate what you have already received', 'Diňe alnan zatlary baha berip bolýar'],
  'g.rating': ['Оценка', 'Rating', 'Baha'],
  'g.comment': ['Комментарий (по желанию)', 'Comment (optional)', 'Düşündiriş (islege görä)'],
  'g.pickRating': ['Поставьте оценку от 1 до 5', 'Give a rating from 1 to 5', '1-den 5-e çenli baha beriň'],
  'g.reviewSaved': ['Отзыв сохранён', 'Review saved', 'Syn saklandy'],

  // GSO app (read-only, guards shown by number only)
  'gso.title': ['Униформа · GSO', 'Uniform · GSO', 'Uniform · GSO'],
  'gso.nav.guards': ['Охранники', 'Guards', 'Garawullar'],
  'gso.nav.orders': ['Заказы', 'Orders', 'Sargytlar'],
  'gso.nav.signed': ['Выдачи', 'Issuances', 'Bermeler'],
  'gso.guardsSub': ['Только номера. Лимит на охранника в год: {limit}', 'Numbers only. Yearly limit per guard: {limit}', 'Diňe belgiler. Bir garawul üçin ýyllyk limit: {limit}'],
  'gso.date': ['Дата', 'Date', 'Sene'],
  'gso.prevFy': ['прошлый фингод', 'previous fiscal year', 'öňki maliýe ýyly'],
};
