// [ru, en, tk]. Turkmen strings are a best-effort draft and need review by a native speaker.
export const SHARED = {
  'common.close': ['Закрыть', 'Close', 'Ýapmak'],
  'common.confirm': ['Подтвердите', 'Please confirm', 'Tassyklaň'],
  'common.yes': ['Да', 'Yes', 'Hawa'],
  'common.cancel': ['Отмена', 'Cancel', 'Ýatyr'],
  'common.save': ['Сохранить', 'Save', 'Ýatda sakla'],
  'common.saved': ['Сохранено', 'Saved', 'Saklandy'],
  'common.done': ['Готово', 'Done', 'Taýýar'],
  'common.loading': ['Загрузка…', 'Loading…', 'Ýüklenýär…'],
  'common.refresh': ['Обновить', 'Refresh', 'Täzele'],
  'common.back': ['Назад', 'Back', 'Yza'],
  'common.nothing': ['Ничего не найдено', 'Nothing found', 'Hiç zat tapylmady'],
  'common.copy': ['Копировать', 'Copy', 'Göçür'],
  'common.copied': ['Скопировано', 'Copied', 'Göçürildi'],
  'common.remove': ['Удалить', 'Remove', 'Aýyr'],
  'common.active': ['Активен', 'Active', 'Işjeň'],
  'common.inactive': ['Отключён', 'Disabled', 'Öçürilen'],

  'err.notEntitled': ['Эта вещь вам пока не положена', 'You are not due for this item yet', 'Bu zat size entek degişli däl'],
  'err.sizeNotSet': ['Сначала укажите размер в профиле', 'Set your size in your profile first', 'Ilki profilde ölçegiňizi giriziň'],
  'err.qtyNorm': ['Количество больше нормы', 'Quantity is above the norm', 'Mukdar kadadan köp'],
  'err.stock': ['Недостаточно на складе', 'Not enough in stock', 'Ammarda ýeterlik ýok'],
  'err.inGroup': ['Вы уже в активной группе', 'You are already in an active group', 'Siz eýýäm işjeň toparda'],
  'err.forbidden': ['Нет прав на это действие', 'You are not allowed to do this', 'Bu hereket üçin hukugyňyz ýok'],
  'err.noteRequired': ['Нужна письменная заметка', 'A written note is required', 'Ýazmaça bellik zerur'],
  'err.reasonRequired': ['Для срочной выдачи укажите причину', 'Give a reason for an urgent issuance', 'Gyssagly bermek üçin sebäbi görkeziň'],
  'err.sizeRequired': ['Укажите размер в каждой строке', 'Size is required on every line', 'Her setirde ölçegi görkeziň'],
  'err.banned': ['Аккаунт отключён', 'This account is disabled', 'Bu hasap öçürilen'],
  'err.badLogin': ['Неверный логин или пароль', 'Wrong login or password', 'Login ýa-da parol nädogry'],
  'err.duplicate': ['Такая запись уже есть', 'This already exists', 'Bu eýýäm bar'],
  'err.sizeNotAllowed': ['Такого размера нет в списке', 'This size is not in the list', 'Bu ölçeg sanawda ýok'],
  'err.immutable': ['Подписанные записи менять нельзя', 'Signed records cannot be changed', 'Gol çekilen ýazgylary üýtgedip bolmaýar'],
  'err.lastOwner': ['Нельзя отключить последнего главного админа', 'The last main admin cannot be disabled', 'Soňky baş administratory öçürmek bolmaýar'],
  'err.selfDeactivate': ['Нельзя отключить самого себя', 'You cannot disable yourself', 'Özüňizi öçürip bolmaýar'],
  'err.nothingToClose': ['Закрывать нечего', 'Nothing left to close', 'Ýapmaga zat ýok'],
  'err.network': ['Нет связи с сервером', 'Cannot reach the server', 'Serwere baglanyp bolmady'],
  'err.unknown': ['Что-то пошло не так', 'Something went wrong', 'Bir zat nädogry boldy'],
  'err.wrongApp': ['Этот аккаунт не для этого приложения', 'This account is not for this app', 'Bu hasap bu programma üçin däl'],

  'auth.logout': ['Выйти', 'Sign out', 'Çykmak'],
  'auth.signIn': ['Войти', 'Sign in', 'Girmek'],
  'auth.number': ['Номер охранника', 'Guard number', 'Garawulyň belgisi'],
  'auth.login': ['Логин', 'Login', 'Login'],
  'auth.pin': ['PIN-код (6 цифр)', 'PIN (6 digits)', 'PIN (6 sany san)'],
  'auth.password': ['Пароль', 'Password', 'Parol'],
  'auth.language': ['Язык', 'Language', 'Dil'],
  'auth.hintGuard': ['Введите свой номер и PIN', 'Enter your number and PIN', 'Belgiňizi we PIN-i giriziň'],
  'auth.hintStaff': ['Введите логин и пароль', 'Enter your login and password', 'Login we paroly giriziň'],

  'pw.title': ['Задайте свой пароль', 'Choose your own password', 'Öz parolyňyzy saýlaň'],
  'pw.introPin': ['Временный PIN нужно заменить на свой. Он будет нужен при каждом входе и при подписи.', 'Replace the temporary PIN with your own. You will need it to sign in and to sign.', 'Wagtlaýyn PIN-i öz PIN-iňiz bilen çalşyň. Ol girmek we gol çekmek üçin gerek.'],
  'pw.introPass': ['Временный пароль нужно заменить на свой.', 'Replace the temporary password with your own.', 'Wagtlaýyn paroly öz parolyňyz bilen çalşyň.'],
  'pw.newPin': ['Новый PIN (6 цифр)', 'New PIN (6 digits)', 'Täze PIN (6 sany san)'],
  'pw.newPass': ['Новый пароль (от 6 символов)', 'New password (6+ characters)', 'Täze parol (azyndan 6 belgi)'],
  'pw.repeat': ['Повторите', 'Repeat', 'Gaýtalaň'],
  'pw.save': ['Сохранить и войти', 'Save and continue', 'Sakla we dowam et'],
  'pw.mismatch': ['Значения не совпадают', 'The two entries do not match', 'Ikisi gabat gelmeýär'],
  'pw.pinRule': ['PIN — ровно 6 цифр', 'PIN must be exactly 6 digits', 'PIN takyk 6 sany san bolmaly'],
  'pw.passRule': ['Пароль — не меньше 6 символов', 'Password must be at least 6 characters', 'Parol azyndan 6 belgi bolmaly'],

  'src.request': ['По заявке', 'Request', 'Haýyş boýunça'],
  'src.group': ['Группа', 'Group', 'Topar'],
  'src.urgent': ['Срочно', 'Urgent', 'Gyssagly'],
  'src.manual': ['Вручную', 'Manual', 'El bilen'],
  'status.pending': ['Ждёт подписи', 'Awaiting signature', 'Gol garaşylýar'],
  'status.signed': ['Подписано', 'Signed', 'Gol çekildi'],
  'status.cancelled': ['Отменено', 'Cancelled', 'Ýatyryldy'],
  'status.open': ['Открыта', 'Open', 'Açyk'],
  'order.ordered': ['Заказан', 'Ordered', 'Sargyt edildi'],
  'order.partial': ['Частично', 'Partly received', 'Bölekleýin'],
  'order.received': ['Получен', 'Received', 'Alyndy'],
  'group.forming': ['Собирается', 'Forming', 'Ýygnanýar'],
  'group.slotSet': ['Выбрано время', 'Time chosen', 'Wagt saýlandy'],
  'group.confirmed': ['Подтверждена', 'Confirmed', 'Tassyklandy'],
  'group.dissolved': ['Распалась', 'Dissolved', 'Dargady'],
  'group.completed': ['Завершена', 'Completed', 'Tamamlandy'],
  'member.invited': ['Приглашён', 'Invited', 'Çagyryldy'],
  'member.joined': ['Участвует', 'Joined', 'Goşuldy'],
  'member.confirmed': ['Подтвердил', 'Confirmed', 'Tassyklady'],
  'member.declined': ['Отказался', 'Declined', 'Ret etdi'],
  'season.summer': ['Лето', 'Summer', 'Tomus'],
  'season.winter': ['Зима', 'Winter', 'Gyş'],
  'season.all_year': ['Круглый год', 'All year', 'Ýylyň dowamynda'],
  'ship.land': ['Наземная', 'Land', 'Gury ýol'],
  'ship.air': ['Авиа', 'Air', 'Awia'],
  'role.guard': ['Охранник', 'Guard', 'Garawul'],
  'role.admin': ['Админ', 'Admin', 'Administrator'],
  'role.owner': ['Главный админ', 'Main admin', 'Baş administrator'],
  'role.gso': ['GSO', 'GSO', 'GSO'],
};
